[build]
  command = "npm run build"
  publish = "dist" # or .next, build, etc. depending on framework

[[edge_functions]]
  path = "/hello"
  function = "hello"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[build.environment]
  NODE_VERSION = "20.12.2"
